//! Pull request creation — builds PR body and creates PRs via `gh` CLI

use crate::delivery::changelog::TaskRecord;
use crate::delivery::config::GitPlatform;
use crate::error::{Result, ZcodeError};
use tokio::process::Command;

/// Options for creating a pull request
#[derive(Debug, Clone)]
pub struct PrOptions {
    /// PR title
    pub title: String,
    /// PR body (markdown)
    pub body: String,
    /// Target base branch
    pub base_branch: String,
    /// Optional labels
    pub labels: Option<Vec<String>>,
    /// Whether to create as draft
    pub draft: bool,
}

/// Result of PR creation
#[derive(Debug, Clone)]
pub struct PrResult {
    /// URL of the created PR
    pub url: String,
}

/// Pull request creator — supports GitHub (`gh`), GitLab (`glab`), and custom commands
pub struct PullRequestCreator {
    platform: GitPlatform,
}

impl PullRequestCreator {
    /// Create a new PR creator for the given platform
    pub fn new(platform: GitPlatform) -> Self {
        Self { platform }
    }

    /// Create a pull request with the given options
    pub async fn create(&self, opts: &PrOptions) -> Result<PrResult> {
        let mut cmd = match &self.platform {
            GitPlatform::GitHub => self.gh_pr_create(opts),
            GitPlatform::GitLab => self.glab_mr_create(opts),
            GitPlatform::Gitea => self.gitea_pr_create(opts),
            GitPlatform::Bitbucket => self.bitbucket_pr_create(opts),
            GitPlatform::Custom { cli_command } => self.custom_pr_create(cli_command, opts),
        };

        let output = cmd
            .output()
            .await
            .map_err(|e| ZcodeError::InternalError(format!("Failed to run PR command: {}", e)))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(ZcodeError::InternalError(format!(
                "PR creation failed: {}",
                stderr
            )));
        }

        let stdout = String::from_utf8_lossy(&output.stdout);
        let url = Self::parse_pr_url(&stdout).ok_or_else(|| {
            ZcodeError::InternalError(format!(
                "Could not parse PR URL from output: {}",
                stdout
            ))
        })?;

        Ok(PrResult { url })
    }

    /// Build a markdown PR body from tasks, changelog, and verification scores
    pub fn build_pr_body(
        tasks: &[TaskRecord],
        changelog: &str,
        scores: &[(String, f64)],
    ) -> String {
        let mut body = String::new();

        body.push_str("## Summary\n\n");
        body.push_str(&format!("{} tasks completed.\n\n", tasks.len()));

        body.push_str("## Task Details\n\n");
        body.push_str("| Task | Score | Status |\n");
        body.push_str("|------|-------|--------|\n");
        for task in tasks {
            let score = task
                .final_score
                .map(|s| format!("{:.0}/100", s))
                .unwrap_or_else(|| "-".to_string());
            let truncated: String = task.task.chars().take(60).collect();
            body.push_str(&format!(
                "| {} | {} | {} |\n",
                truncated, score, task.status
            ));
        }

        body.push_str("\n\n## Verification Scores\n\n");
        for (name, score) in scores {
            body.push_str(&format!("- **{}**: {:.1}/100\n", name, score));
        }

        body.push_str("\n\n## Changelog\n\n");
        body.push_str(changelog);

        body.push_str("\n\n---\n");
        body.push_str("Generated by [zcode](https://github.com/user/zcode)");

        body
    }

    /// Parse the PR URL from CLI output
    pub fn parse_pr_url(output: &str) -> Option<String> {
        // gh outputs the URL, possibly preceded by metadata
        for line in output.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("https://") && trimmed.contains("/pull/") {
                return Some(trimmed.to_string());
            }
            // GitLab merge request URL
            if trimmed.starts_with("https://") && trimmed.contains("/merge_requests/") {
                return Some(trimmed.to_string());
            }
        }
        // Fallback: try to find any URL in the output
        for word in output.split_whitespace() {
            if word.starts_with("https://") && (word.contains("/pull/") || word.contains("/merge_requests/")) {
                return Some(word.to_string());
            }
        }
        None
    }

    fn gh_pr_create(&self, opts: &PrOptions) -> Command {
        let mut cmd = Command::new("gh");
        cmd.args([
            "pr",
            "create",
            "--title",
            &opts.title,
            "--body",
            &opts.body,
            "--base",
            &opts.base_branch,
        ]);
        if let Some(labels) = &opts.labels {
            cmd.arg("--label").arg(labels.join(","));
        }
        if opts.draft {
            cmd.arg("--draft");
        }
        cmd
    }

    fn glab_mr_create(&self, opts: &PrOptions) -> Command {
        let mut cmd = Command::new("glab");
        cmd.args([
            "mr",
            "create",
            "--title",
            &opts.title,
            "--description",
            &opts.body,
            "--target-branch",
            &opts.base_branch,
        ]);
        if let Some(labels) = &opts.labels {
            cmd.arg("--label").arg(labels.join(","));
        }
        if opts.draft {
            cmd.arg("--draft");
        }
        cmd
    }

    fn gitea_pr_create(&self, opts: &PrOptions) -> Command {
        let mut cmd = Command::new("tea");
        cmd.args([
            "pulls",
            "create",
            "--title",
            &opts.title,
            "--description",
            &opts.body,
            "--base",
            &opts.base_branch,
        ]);
        if let Some(labels) = &opts.labels {
            for label in labels {
                cmd.arg("--labels").arg(label);
            }
        }
        cmd
    }

    fn bitbucket_pr_create(&self, opts: &PrOptions) -> Command {
        // Bitbucket uses the same gh-compatible interface via Bitbucket CLI
        let mut cmd = Command::new("bb");
        cmd.args([
            "pr",
            "create",
            "--title",
            &opts.title,
            "--description",
            &opts.body,
            "--destination",
            &opts.base_branch,
        ]);
        cmd
    }

    fn custom_pr_create(&self, cli_command: &str, opts: &PrOptions) -> Command {
        let mut cmd = Command::new("sh");
        cmd.arg("-c")
            .arg(format!(
                "{} create-pr --title '{}' --body '{}' --base '{}'",
                cli_command,
                opts.title.replace('\'', "'\\''"),
                opts.body.replace('\'', "'\\''"),
                opts.base_branch,
            ));
        cmd
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_task(desc: &str, score: Option<f64>) -> TaskRecord {
        TaskRecord {
            task: desc.to_string(),
            final_score: score,
            status: "completed".to_string(),
        }
    }

    #[test]
    fn test_build_pr_body_basic() {
        let tasks = vec![make_task("Add auth module", Some(90.0))];
        let changelog = "# Changelog\n\n## Features\n\n- Add auth module\n";
        let scores = vec![("tests".to_string(), 95.0)];

        let body = PullRequestCreator::build_pr_body(&tasks, changelog, &scores);

        assert!(body.contains("## Summary"));
        assert!(body.contains("1 tasks completed"));
        assert!(body.contains("## Task Details"));
        assert!(body.contains("Add auth module"));
        assert!(body.contains("90/100"));
        assert!(body.contains("## Verification Scores"));
        assert!(body.contains("tests"));
        assert!(body.contains("95.0/100"));
        assert!(body.contains("## Changelog"));
        assert!(body.contains("Generated by [zcode]"));
    }

    #[test]
    fn test_build_pr_body_multiple_tasks() {
        let tasks = vec![
            make_task("Fix login bug", Some(85.0)),
            make_task("Add new dashboard", Some(92.0)),
            make_task("Refactor database", Some(78.0)),
        ];
        let body = PullRequestCreator::build_pr_body(&tasks, "", &[]);
        assert!(body.contains("3 tasks completed"));
        assert!(body.contains("Fix login bug"));
        assert!(body.contains("Add new dashboard"));
        assert!(body.contains("Refactor database"));
    }

    #[test]
    fn test_build_pr_body_no_score() {
        let tasks = vec![make_task("Some task", None)];
        let body = PullRequestCreator::build_pr_body(&tasks, "", &[]);
        assert!(body.contains("-"));
    }

    #[test]
    fn test_build_pr_body_long_description_truncated() {
        let long_desc = "A".repeat(100);
        let tasks = vec![make_task(&long_desc, Some(80.0))];
        let body = PullRequestCreator::build_pr_body(&tasks, "", &[]);
        // The description should be truncated to 60 chars in the table
        let task_line = body.lines().find(|l| l.contains("AAA")).unwrap();
        assert!(task_line.len() < 200); // rough check that truncation happened
    }

    #[test]
    fn test_parse_pr_url_github() {
        let output = "https://github.com/owner/repo/pull/42\n";
        let url = PullRequestCreator::parse_pr_url(output);
        assert_eq!(
            url,
            Some("https://github.com/owner/repo/pull/42".to_string())
        );
    }

    #[test]
    fn test_parse_pr_url_gitlab() {
        let output = "https://gitlab.com/owner/repo/-/merge_requests/7\n";
        let url = PullRequestCreator::parse_pr_url(output);
        assert_eq!(
            url,
            Some("https://gitlab.com/owner/repo/-/merge_requests/7".to_string())
        );
    }

    #[test]
    fn test_parse_pr_url_with_prefix() {
        let output = "Creating pull request...\nhttps://github.com/owner/repo/pull/10\n";
        let url = PullRequestCreator::parse_pr_url(output);
        assert!(url.is_some());
        assert!(url.unwrap().contains("/pull/10"));
    }

    #[test]
    fn test_parse_pr_url_none() {
        let output = "something went wrong";
        let url = PullRequestCreator::parse_pr_url(output);
        assert!(url.is_none());
    }

    #[test]
    fn test_parse_pr_url_empty() {
        let url = PullRequestCreator::parse_pr_url("");
        assert!(url.is_none());
    }

    #[test]
    fn test_pr_creator_new_github() {
        let creator = PullRequestCreator::new(GitPlatform::GitHub);
        // Just verify construction works
        let _ = &creator;
    }

    #[test]
    fn test_pr_options_fields() {
        let opts = PrOptions {
            title: "Test PR".into(),
            body: "Body text".into(),
            base_branch: "main".into(),
            labels: Some(vec!["enhancement".into()]),
            draft: true,
        };
        assert_eq!(opts.title, "Test PR");
        assert!(opts.draft);
        assert!(opts.labels.is_some());
    }

    #[test]
    fn test_pr_result_fields() {
        let result = PrResult {
            url: "https://github.com/owner/repo/pull/1".to_string(),
        };
        assert_eq!(result.url, "https://github.com/owner/repo/pull/1");
    }
}
